--- #YAML:1.0
name:                Thread-Pool-Simple
version:             0.24
abstract:            ~
license:             ~
author:              
    - Jianyuan Wu <jwu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
